repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
    - id: isort
      args: [--check]
      language_version: python 3.8

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [--check]
      language_version: python3.8
